// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDa5veQzn5B1P6bBkJmu-F8qRlIMf6BQU',
    appId: '1:434833307990:web:7f5399e08c9262f1bcfef7',
    messagingSenderId: '434833307990',
    projectId: 'uts-clone',
    authDomain: 'uts-clone.firebaseapp.com',
    storageBucket: 'uts-clone.appspot.com',
    measurementId: 'G-9FQQ3QFX3C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhG8cwcNUOmdejbz3nRkDxN7baGPmer_c',
    appId: '1:434833307990:android:5bb25e82ed6ddde6bcfef7',
    messagingSenderId: '434833307990',
    projectId: 'uts-clone',
    storageBucket: 'uts-clone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaGV9OVVIeLj6_fMnd2901szjPPi8Fd_A',
    appId: '1:434833307990:ios:abefd12f09f05d8dbcfef7',
    messagingSenderId: '434833307990',
    projectId: 'uts-clone',
    storageBucket: 'uts-clone.appspot.com',
    iosBundleId: 'com.example.uts',
  );
}
